import java.io.*;

public class Main 
{

	public static void main(String[] args) 
	{
		FileWriter f;
		PrintWriter fout;
		String uk;
		if(args.length<1)
		{
			System.out.println("Usage:\ncust-rest-gen.jar [unlock key]");
			return;
		}
		uk=args[0];
		if(uk.length()!=16)
		{
			System.out.println("Error: Unlock key seems to be wrong");
			return;
		}
		
		try
		{
			f = new FileWriter("cust-reset.ta");
			fout = new PrintWriter(f);
		}
		catch(Exception e)
		{
			System.out.println("Error: I can't make file\n"+e.toString());
			return;
		}
		
		fout.write("//===========================================================\n"
				+"// Active customization reset\n"
				+"// Generated by cust-rest-gen by Andrea993\n"
				+"// Unlock the bootloader\n"
				+"//===========================================================\n"
				+ "02\n"
				+"000008B2 0010");
		
		for(int i=0;i<uk.length();i++)
		{
			fout.write(" "+charToHex(uk.charAt(i)));
		}
				
		fout.flush();
		fout.close();
		
		System.out.println("DONE");
	}
	
	static String charToHex(char c)
	{
		return Integer.toHexString((int)c);
	}
	

}

